cache: pip
matrix:
  include:
    - os: linux
      sudo: required
      language: python
      python: 2.7
      env: "TOXENV=pep8 ARTIFACTS_BUCKET=pyfalinuxbuilds ARTIFACTS_PATHS=\"/home/travis/build/pyfa_linux.zip:/home/travis/build/pyfa_mac_debug.zip:./build/pyfa/warnpyfa.txt\""
    - os: osx
      language: generic
      python: 2.7
      env: "TOXENV=pep8 ARTIFACTS_BUCKET=pyfaosxbuilds ARTIFACTS_PATHS=\"./pyfa_mac.zip:./pyfa_mac_debug.zip:./build/pyfa/warnpyfa.txt\""
addons:
  apt:
    packages:
before_install:
  - pip install tox
  # We're not actually installing Tox, but have to run it before we install wxPython via Conda. This is fugly but vOv
  - tox
  # Update the environment
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install libatk-adaptor libgail-common;
      sudo apt-get install libatk-adaptor:i386 libgail-common:i386;
      sudo apt-get install gtk2-engines;
      sudo apt-get install gtk2-engines-*;
      sudo apt-get install libfreetype6-dev;
      sudo apt-get install fonts-cantarell lmodern ttf-aenigma ttf-georgewilliams ttf-bitstream-vera ttf-sjfonts ttf-tuffy tv-fonts;
      sudo apt-get install ubuntustudio-font-meta;
      sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-ru language-pack-he language-pack-zh-hans;
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ln -s /usr/X11R6/share/fonts /usr/share;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install graphviz;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  # install wxPython 3.0.0.0
  - conda install -c https://conda.anaconda.org/travis wxpython
before_script:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
script:
  - py.test --cov=./
after_success:
  # Upload coverage data
  - bash <(curl -s https://codecov.io/bash)

  # Install requirements to build the package
  - pip install -r requirements_build.txt

  # copy pyinstaller build files into place
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cp /home/travis/build/Pyfa-fit/Pyfa-fit/dist_assets/linux/pyfa.spec /home/travis/build/Pyfa-fit/Pyfa-fit/pyfa.spec;
      cp /home/travis/build/Pyfa-fit/Pyfa-fit/dist_assets/linux/pyfa_debug.spec /home/travis/build/Pyfa-fit/Pyfa-fit/pyfa_debug.spec;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "mac" ]]; then
      cp ./dist_assets/mac/pyfa.spec ./pyfa.spec;
      cp ./dist_assets/mac/pyfa_debug.spec ./pyfa_debug.spec;
    fi

  # Run build
  - pyinstaller --clean --noconfirm --windowed ./pyfa.spec

  # zip builds
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cd /home/travis/build/Pyfa-fit/Pyfa-fit/dist/;
      zip -r /home/travis/build/pyfa_linux.zip /home/travis/build/Pyfa-fit/Pyfa-fit/dist/pyfa;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "mac" ]]; then
      zip -r ./pyfa_mac.zip ./dist/pyfa;
    fi

  # Run build (debug)
  - pyinstaller --clean --noconfirm --windowed pyfa_debug.spec

  # zip build (debug)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cd /home/travis/build/Pyfa-fit/Pyfa-fit/dist/;
      zip -r /home/travis/build/pyfa_linux_debug.zip /home/travis/build/Pyfa-fit/Pyfa-fit/dist/pyfa;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "mac" ]]; then
      zip -r ./pyfa_mac_debug.zip ./dist/pyfa;
    fi

  # Debugging
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ls /home/travis/build/Pyfa-fit/Pyfa-fit/;
    fi

  - ls
  - ls /usr/share/fonts

  # Old build
  # $ ls /usr/share/fonts
  # truetype  type1  X11

addons:
    artifacts:
        s3_region: "us-west-2"
