cache: pip
matrix:
  include:
    - os: linux
      sudo: required
      language: python
      python: 2.7
      env: "TOXENV=pep8 ARTIFACTS_BUCKET=pyfalinuxbuilds ARTIFACTS_PATHS=\"./pyfa.zip:./pyfa_debug.zip:./build/pyfa/warnpyfa.txt\""
    - os: osx
      language: generic
      python: 2.7
      env: "TOXENV=pep8 ARTIFACTS_BUCKET=pyfaosxbuilds ARTIFACTS_PATHS=\"./pyfa.zip:./pyfa_debug.zip:./build/pyfa/warnpyfa.txt\""
addons:
  apt:
    packages:
before_install:
  - pip install tox
  # We're not actually installing Tox, but have to run it before we install wxPython via Conda. This is fugly but vOv
  - tox
  # Update the environment
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-ru language-pack-he language-pack-zh-hans;
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install graphviz;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  # install wxPython 3.0.0.0
  - conda install -c https://conda.anaconda.org/travis wxpython
before_script:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
script:
  - py.test --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - pip install -r requirements_build_linux.txt
  - sudo apt-get install libfreetype6-dev
  - cp /home/travis/build/Pyfa-fit/Pyfa-fit/dist_assets/linux/pyfa.spec /home/travis/build/Pyfa-fit/Pyfa-fit/pyfa.spec
  - cp /home/travis/build/Pyfa-fit/Pyfa-fit/dist_assets/linux/pyfa_debug.spec /home/travis/build/Pyfa-fit/Pyfa-fit/pyfa_debug.spec
  - pyinstaller --clean --noconfirm --windowed pyfa.spec
  - zip -r /home/travis/build/Pyfa-fit/Pyfa-fit/pyfa.zip /home/travis/build/Pyfa-fit/Pyfa-fit/dist/pyfa
  - pyinstaller --clean --noconfirm --windowed pyfa_debug.spec
  - zip -r /home/travis/build/Pyfa-fit/Pyfa-fit/pyfa_debug.zip /home/travis/build/Pyfa-fit/Pyfa-fit/dist/pyfa
  - ls /home/travis/build/Pyfa-fit/Pyfa-fit/
  - ls /home/travis/build/Pyfa-fit/Pyfa-fit/dist/pyfa
addons:
  artifacts: true
  s3_region: "us-west-2"
